### ISSUE TITLE
Create commands for controlling decorated tabs

### ISSUE THREAD

**Issue by david-tejada** [david-tejada/rango#101]
As of now there's not an easy way to focus a specific tab, so if you want to focus a specific tab your options are to estimate which tab number it is (if it's one of the first 8 tabs) or using `tab last` or `tab next` and maybe some repeater commands or sounds. Some people also use tab search for this purpose. All these methods are inefficient and tedious.

My idea to make all this easier is to prepend some decoration to the page title, which is the only way we have to changed the appearance of the tab. Using a combination of colors (🔴🔵🟢🟡🟣) and letters we can have a nice system that is quick to use, not unlike direct clicking.

<img width="721" alt="Screenshot 2023-04-26 at 13 51 22" src="https://user-images.githubusercontent.com/3219671/234566404-ee8830c6-9965-4f9c-84cf-686d3f7ab927.png">

So, for example, in this example using the command `red air` would focus the second tab.

Once the tabs are decorated we can use those decorators not just for focusing the tabs but also to move or close them. We could also create complex commands like `close red air past yellow cap` or  `move blue gust and red drum before red fine`. I don't know if creating such commands is overcomplicating things or if people would find them useful.

**Comment by pokey** [comment]
Cool idea but i wonder if that's going to lead to cursorless conflicts when we start integrating things 🤔. Maybe would be fine because actions are different? Alternately you could use some other kind of symbol, eg different emoji. Or just use letters with a prefix to avoid rango mark conflict, eg "close tab air". The consistency might be nice, eg "close tab" / "close tab air". Or "swap tab with bat", where "tab" without a mark indicates current tab, and use cursorless-style inference to infer that "bat" is a tab. Idk just stream of consciousness here 😄

**Comment by david-tejada** [comment]
What if we switch it? Instead of `red air` we use `air red`

**Comment by pokey** [comment]
Could work? As long as you swapped the letter with the color in the tab display obv

Would be curious to hear @andreasarvidsson's thoughts here

**Comment by david-tejada** [comment]
Yes, of course, I would swap in the tab too

**Comment by AndreasArvidsson** [comment]
@pokey I'm probably not the right person to ask since I very seldom have more tabs open that can be easily accessible by numbers. I actually don't use the tabs feature in Rango. In general having both cursorless and Rango refer to colored letters might be confusing though.

**Comment by david-tejada** [comment]
Maybe using a prefix like @pokey mentions is the right idea. In most cases is going to be the same number of syllables if we use something like `tab gust`. Only beyond tab 26 one would have to use three syllables.

**Comment by pokey** [comment]
There's no way to underline letters in the tab? Could do cursorless-style thing. But just putting letter at the beginning is prob fine

**Comment by david-tejada** [comment]
No, the only way to mark a tab is to change the document.title

**Comment by david-tejada** [comment]
For the moment I have just implemented the functionality to activate tabs. For more complex commands I need to first complete #136
