### ISSUE TITLE
Implement range target

### ISSUE THREAD

**Issue by david-tejada** [david-tejada/rango#104]
I think this command could be useful to, for example, clicking adjacent checkboxes or copy elements to the clipboard.

For example, `near past zip`:

![past-target](https://user-images.githubusercontent.com/3219671/234787580-105f3931-47c1-468a-a298-fa6ba1272d0a.gif)

**Comment by pokey** [comment]
To what extent can we rely on the document element order matching the user's expectation?

**Comment by david-tejada** [comment]
For the main use cases I imagine I think we can rely on it. I can check which element comes first in the dom so it doesn't matter if the user says `near past zip` or `zip past near`.

Do you have any case in mind? I know you can change the order of the elements using something like the flexbox order property but I don't think it's used much and I think it's considered bad practice to alter the visual order like that.

**Comment by pokey** [comment]
Nope mostly just armchair curiosity, and wondering how bad the failure mode is, eg I imagine it clicking every link on some gigantic page full of ads 😅
