### ISSUE TITLE
Add ability to copy links to clipboard

### ISSUE THREAD

**Issue by richardmcmillen** [david-tejada/rango#11]
This would be a really great addition and is pretty much one of the last main features I used from Vimium.

It would be nice to have a subtle signal/notification, maybe by the alphabet characters you just used, that the action was successful. Kinda like this but aligned with the size and style of rango.

<img width="451" alt="image" src="https://user-images.githubusercontent.com/298026/165698454-442a5c25-5293-470b-91b6-9dcf41b36e90.png">

**Comment by david-tejada** [comment]
Nice idea, I think this will be very useful for a lot of people. I'm gonna have to send the link back to talon to copy it to the clipboard since we use the clipboard for messaging but it shouldn't be too complicated.

**Comment by david-tejada** [comment]
This is implemented. I will probably implement a couple of more things and then submit to the store.
