### ISSUE TITLE
Try to publish Rango to the Safari App Store

### ISSUE THREAD

**Issue by david-tejada** [david-tejada/rango#140]
> I think if you can add a right-click menu to the toolbar icon and keyboard clicking with some kind of onboarding/help, it might be friendly enough to submit

@nriley I think you mean left click? [Popups - Mozilla | MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Popups)

As onboarding I could just open a new page similar to the What's New page with instructions on how to use Rango with and without talon.

**Comment by nriley** [comment]
Nope I mean a menu, though a popup would be friendly and more discoverable. 

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/ContextType

**Comment by david-tejada** [comment]
Right, I wasn't sure you could add items to the action button context menu but it seems you can. That's probably going to be easier for now

**Comment by david-tejada** [comment]
Related:
- [x] #156 
- [x] #157
