### ISSUE TITLE
 keyboard input not working on https://dict.leo.org/german-english/rango

### ISSUE THREAD

**Issue by gpunktschmitz** [david-tejada/rango#144]
I've set up keyboard input to the hotkey `CTRL + ALT + F` in the extension but when I want to use the keyboard input on https://dict.leo.org it focuses the input/search field after the first key is pressed. using talon/voice input the site works as expected.

**Comment by david-tejada** [comment]
Confirmed. I need to stop propagation of the keyboard event. Will be fixed for next release.
