### ISSUE TITLE
Not able to click element in google mail - other UI elements aren't markedup with hint

### ISSUE THREAD

**Issue by richardmcmillen** [david-tejada/rango#15]
I haven't noticed this anywhere else yet but I have problems selecting the checkbox in the top left of google mail to select all unread mail. Saying the letter hint performs the animation of the hint but the checkbox is not selected. This does work with Vimium but I haven't looked at what could be the difference yet.

![image](https://user-images.githubusercontent.com/298026/166207937-f6a52e1f-8506-4f2f-acae-5a72a9264c3b.png)
![image](https://user-images.githubusercontent.com/298026/166208125-c09a365a-ccb6-4d66-8162-707379293836.png)

Another thing I saw was that in the google mail UI some clickable elements with Vimium aren't marked up with hints in rango

Rango:
![image](https://user-images.githubusercontent.com/298026/166209270-a07cb7a4-589a-4bef-a0e5-fd74658e3b38.png)

Vimium:
![image](https://user-images.githubusercontent.com/298026/166209332-c880fae6-e355-4f99-8212-501550911a6c.png)

**Comment by david-tejada** [comment]
The first one easy. I already have a fix.

For this second issue I don't see that menu in gmail, I guess it's related to hangouts. I guess that's an iframe, Gmail has a lot of iframes. Vimium has support for those but we still don't have it. iframes are complicated and I need to take a look at their code to see how they solved it

**Comment by david-tejada** [comment]
#16

**Comment by david-tejada** [comment]
I fixed the checkbox. I will close this issue and keep #16 open.

**Comment by richardmcmillen** [comment]
Awesome, thanks!!
