### ISSUE TITLE
hide tab markers when clicking the rango extension icon

### ISSUE THREAD

**Issue by gpunktschmitz** [david-tejada/rango#184]
I sometimes use the mouse to toggle hints by clicking the rango extension icon - it would be nice if also the tab markers where hidden then.

**Comment by david-tejada** [comment]
Makes sense. I'll probably need to add a setting in case some users don't want that behavior.

**Comment by david-tejada** [comment]
Clicking on the action button will toggle tab markers keeping them in sync with the global hints toggle. I ended up not adding the setting to opt out of this. I will consider adding it if someone complains.
