### ISSUE TITLE
Closing tabs by slot

### ISSUE THREAD

**Issue by nriley** [david-tejada/rango#189]
Now we can refer to tabs with targets, it would be great if you could use targets to close one or more tabs. Here's an example of how I worked around this for a single tab although it would be great to do this without activating the tab:

```
close <user.rango_target>:
    user.rango_command_with_target("activateTab", rango_target)
    user.tab_close_wrapper()
```

Could also be pronounced "tab close" for consistency.

A couple additions that I'd definitely use:

* Closing a contiguous range of tabs using slots: "close fine past look".
* Even more cursorless-like — "close host fine" to close all the tabs for the host of the tab labeled F.

**Comment by david-tejada** [comment]
~~Depends on #136~~
