### ISSUE TITLE
Settings toggles are invisible in high contrast mode

### ISSUE THREAD

**Issue by bacall213** [david-tejada/rango#192]
The settings toggles become invisible when the OS is in some high contrast modes.

Steps to reproduce for Windows:
1. Navigate to Rango settings
2. Open Settings > Ease of access > high contrast
3. Turn on high contrast and set it to "High Contrast Black"

Steps to reproduce in Chrome (emulated):
1. Navigate to Rango settings
2. Open Chrome Dev Tools
3. On the three dot overflow menu in Dev Tools, select more tools > Rendering
4. Scroll down to "Emulate CSS media feature forced-colors" and set the option to "forced-colors: active"

**Comment by bacall213** [comment]
I think I have a solution for this (that seems to work in my tests). All edits in Toggle.css:

.Toggle button
- Add outline
- Add font-family: sans-serif 
- Add font size

```
.Toggle button {
  --width: 2.5rem;
  --height: calc(var(--width) / 2); 
  display: inline-block;
  position: relative;
  width: var(--width);
  height: var(--height);
  background-color: var(--slate-300);
  border: none;
  outline: 2px solid var(--slate-300);
  border-radius: var(--height);
  transition: background-color 0.4s;
  font-family: sans-serif;
  font-size: calc(var(--height) * 0.7);
}
```

Add new class, .Toggle button::before
- Set content to "O" (capital O as in orange)
- Set position absolute
- Set top and right for positioning of the "O"

```
.Toggle button::before {
  content: "O";
  position: absolute;
  top: calc(var(--height) * 0.08);
  right: calc(var(--height) * 0.3);
}
```

Add new class, .Toggle button[aria-pressed="true"]::before
- Set content to "I" (capital I as in indigo)
- Set position to absolute
- Set top and right for positioning of the "I"

```
.Toggle button[aria-pressed="true"]::before {
  content: "I";
  position: absolute;
  top: calc(var(--height) * 0.08);
  right: calc(var(--height) * 1.2);
}
```

.Toggle button[aria-pressed="true"]
- Add outline

```
.Toggle button[aria-pressed="true"] {
  background-color: var(--green-500);
  outline-color: var(--green-500);
}
```

.Toggle.disabled button[aria-pressed="true"]
- Add outline

```
.Toggle.disabled button[aria-pressed="true"] {
  background-color: var(--slate-300);
  outline-color: var(--slate-300);
}
```

.Toggle button:focus
- Remove outline: none so the toggles don't change shape when you focus or unfocus them

```
.Toggle button:focus {
}
```


How this all comes together is that you end up with an outline around the inner toggle and the background of the toggle that makes it look just a tiny bit thicker when high contrast isn't enabled. When high contrast is enabled, that outline becomes a white line so the toggle becomes visible. Since a color and position were being used to indicate the state but we remove the extra color, adding "O" and "I" to the button provides a secondary way to identify if the toggle is on or off. When the toggle is off, the "O" is visible on right side. When the toggle is on, the "O" is hidden and an "I" is added on the left side. I played around with adding the letter inside of the switch itself, but the spacing around the letter starts to break up the outline and it got a bit messy. I also tried using the full word "on" and "off" and that was also messy.


![forced colors off with focus](https://github.com/david-tejada/rango/assets/5055598/8b824145-a934-4c49-a89d-854b8205a493)
![forced colors off without focus](https://github.com/david-tejada/rango/assets/5055598/6567ddd2-765b-4ea9-997f-3a8366014f96)
![forced colors on with focus](https://github.com/david-tejada/rango/assets/5055598/b361c33f-fd24-4b9c-8545-c6a8b6ff1316)
![forced colors on without focus](https://github.com/david-tejada/rango/assets/5055598/57107393-8e59-491f-9453-8bbb6938479e)

**Comment by david-tejada** [comment]
I'm sorry but I don't like this. There is no need to change the styles when there are no forced colors. The "I" and "O" didn't show vertically centered for me. I also don't think they are particularly intuitive in high contrast mode. 

Also, Safari doesn't respect border radius in outline:
<img width="139" alt="Screenshot 2023-09-19 at 16 10 30" src="https://github.com/david-tejada/rango/assets/3219671/0f5609b4-c9de-47e2-aefa-242576b5ed31">

Check out if #196 and let me know if it works for you. This is how it looks for me:

### Firefox
<img width="678" alt="Screenshot 2023-09-19 at 16 54 22" src="https://github.com/david-tejada/rango/assets/3219671/4bb049c0-64b8-41f9-b1ae-ca35af65f2d2">

### Chrome
<img width="681" alt="Screenshot 2023-09-19 at 16 54 29" src="https://github.com/david-tejada/rango/assets/3219671/766285c8-6ad6-4b78-a158-f5cb0476f0e8">
<img width="677" alt="Screenshot 2023-09-19 at 16 54 39" src="https://github.com/david-tejada/rango/assets/3219671/be40f618-5d1e-439b-8e16-7e34716e711f">

**Comment by bacall213** [comment]
Fair point, I didn't test with Safari or Firefox. The only thing lost is that the slider button disappears for a split second when transitioning from the on state to the off state, but that's just visual eye candy. From a high contrast perspective your solution is great.

**Comment by david-tejada** [comment]
I have improved the overall aesthetics a bit and the transition. Take a look and let me know what you think. It would be nice if you could test with different high contrast themes, from what I have read there's four in Windows.

**Comment by bacall213** [comment]
I like the addition of the animation and the "x", but I noticed the focus highlight remains after the focus has shifted. For example, in high contrast black the off state is a white outline with a black center and white "X". When it's toggled on the state change is reflected by the animation and the outline changing to the highlight color. When focus is shifted to another field that highlight is no longer necessary, but it remains. If a toggle is switched on and then off again and then you move to the next toggle, the prior toggles you've interacted with are stuck with the highlight color as the outline. 

I tested it with Chrome on Windows using high contrast white, black, high contrast 1, and high contrast 2.

High contrast white didn't seem to have any lingering focus outline after moving to the next toggle. There's no screenshot for high contrast white (focused) since it looked the same as unfocused.

High contrast black, high contrast 1, and high contrast 2 each had a lingering outline color. Each of the "focused" screenshots are after I switched the toggle and then went to another toggle so it would no longer have keyboard or mouse focus.

Windows - Chrome - Normal
![windows-chrome-normal](https://github.com/david-tejada/rango/assets/5055598/66d57963-d084-4066-ac1d-1311a28f7a33)

Windows - Chrome - high contrast white - unfocused
![windows-chrome-highcontrast-white-unfocused](https://github.com/david-tejada/rango/assets/5055598/a89a3afa-9c1c-49b5-a545-42abe650ea54)

Windows - Chrome - high contrast 2 - unfocused
![windows-chrome-highcontrast-two-unfocused](https://github.com/david-tejada/rango/assets/5055598/1259d761-bd6f-4bf8-878a-1558e1d5af36)

Windows - Chrome - high contrast 2 - focused
![windows-chrome-highcontrast-two-focused](https://github.com/david-tejada/rango/assets/5055598/4b2e88a9-c4cd-4897-a669-04e87a366211)

Windows - Chrome - high contrast 1- unfocused
![windows-chrome-highcontrast-one-unfocused](https://github.com/david-tejada/rango/assets/5055598/17304449-f3ab-448c-9136-2b2461347f99)

Windows - Chrome - high contrast 1 - focused
![windows-chrome-highcontrast-one-focused](https://github.com/david-tejada/rango/assets/5055598/5b339c05-8e16-4e5f-8e71-cafc81f57bd8)

Windows - Chrome - high contrast black - unfocused
![windows-chrome-highcontrast-black-unfocused](https://github.com/david-tejada/rango/assets/5055598/285624d4-9119-4fce-8a76-c4d13e6a8a97)

Windows - Chrome - high contrast black - focused
![windows-chrome-highcontrast-black-focused](https://github.com/david-tejada/rango/assets/5055598/8310c4cd-d860-4001-ad72-38aaefff57d0)

**Comment by david-tejada** [comment]
Yes, I have noticed that lingering focus state too. I don't know what's causing it. I'll play around with it a bit more to see if I can figure it out.

**Comment by david-tejada** [comment]
Ok, I have removed the focus color from the toggle buttons themselves. The focus can still be perceived from the border around the whole setting. Have also improved the borders of the input and select elements. I have made the borders of the input elements dotted when the input is invalid.

Let me know if it all works fine for you.

**Comment by bacall213** [comment]
Looks good to me!

Here's an updated set of screenshots from each of the Windows high contrast themes. For high contrast 2 I still had keyboard focus on the highlighted section so the highlight box isn't a bug.

High contrast 1

![win-chrome-highcontrast-1](https://github.com/david-tejada/rango/assets/5055598/52c3212f-de25-4ce4-8305-71d2e8a3c489)

High contrast 2

![win-chrome-highcontrast-2](https://github.com/david-tejada/rango/assets/5055598/a1ee64f2-2fdd-47b8-9ae9-a3f11bef1196)

High contrast black

![win-chrome-highcontrast-black](https://github.com/david-tejada/rango/assets/5055598/1f669c8c-fcf3-468d-b94f-57b4343d0e56)

High contrast white

![win-chrome-highcontrast-white](https://github.com/david-tejada/rango/assets/5055598/8776a3f5-ddef-4e0b-a04c-bcaabb4b7409)

**Comment by david-tejada** [comment]
Cool, l'll merge then
