### ISSUE TITLE
Rango keeps leaving explicit mode, and I keep having to ask it to go back to explicit mode

### ISSUE THREAD

**Issue by therealrobster** [david-tejada/rango#199]
Hi all,

As per the subject, I keep going to use rango and it keeps turning off explicit mode.

I'm using the latest firefox on Linux. And I'm using the latest rango as of yesterday.

I can't find a pattern as to what is triggering it, but it is not in the history. I came back from putting talon to sleep just now and saw that explicit mode was off again. So, I tried toggling and un toggling but it made no difference.

Is there any way to completely lock it into explicit mode, so that I don't keep having the issues I'm having?

I want to say thank you from the bottom of my heart for this software, and I really appreciate it, but this one thing is really making it difficult for me and I hope this is an easy fix.

**UPDATE**: I've found one use case that triggers it. If I switch to telegram desktop by saying focus telegram, then switch back to firefox by saying focus firefox, I can see that rango has lost it's explicit mode.

Further testing shows this works with all apps including thunderbird and more. I hope this helps.

**Comment by david-tejada** [comment]
This is strange as explicit clicking is the default mode. Could you reproduce the issue, open the talon debug window and tell me what are the values for the `user.rango_start_with_direct_clicking` setting and if the tag `user.rango_direct_clicking` is active?

Also, check that in `rango.talon` you have this setting on line 4 `user.rango_start_with_direct_clicking = 1`.

**Comment by therealrobster** [comment]
Thanks so much for your reply,

I did some researching but it turns out you have to be on the paid beta to get access to the debug window. 

This is something I'm planning on doing but currently I don't have access to that. So currently this might not be able to go further until I do that.

my rango.talon file contains this:
`  user.rango_start_with_direct_clicking = 1`

So that should be fine I guess.

**Comment by david-tejada** [comment]
I am also using the public version at the moment. I see that the menu to open the debug window is not there but saying `talon debug window` opens it. Try that.

**Comment by therealrobster** [comment]
Thanks for your help with this. When I try and say `talon debug window` it's really strange and it will only let me say `talon debug modes` and nothing happens.  I've been incredibly specific and it just will not accept that saying on my version. For exampl I can say Talon, I can say debug, I can say window, However when I put them together all it does is say `talon debug modes`.

**Comment by david-tejada** [comment]
Oh. I think it's not part of community and I added it myself. Try adding this line to *plugin/talon_helpers/talon_helpers.talon* or other file with global scope:

```talon
^talon debug window$: menu.open_debug_window()
```

**Comment by david-tejada** [comment]
This should be fixed after the last update. You just have to remove the tag to use direct clicking in _rango.talon_.
