### ISSUE TITLE
Editing a rich text field which contains a rango hint submits the hint contained when submitting the form

### ISSUE THREAD

**Issue by richardmcmillen** [david-tejada/rango#20]
I have only witnessed this in Jira but have not gone looking to replicate anywhere else yet.

If you are editing a rich text input area which has a link in it, it is marked up with a rango hint `bq`
![image](https://user-images.githubusercontent.com/298026/170634998-884c062e-842b-4d7d-876a-9903af8c7eec.png)

If you then submit the form the hint letters end up in the saved content - `bq`
![image](https://user-images.githubusercontent.com/298026/170635427-554ba919-9fac-4dcf-b6a7-df2167d1d7e5.png)

**Comment by richardmcmillen** [comment]
Inspecting this HTML 
![image](https://user-images.githubusercontent.com/298026/170642938-8bd7938b-d927-4558-a0b8-c76f0c75b2e0.png)

We can see the whole content editable area is the `body` of an `iframe` 😬
![image](https://user-images.githubusercontent.com/298026/170642845-7f57438e-8fd0-4056-b506-ee0a4d0ae328.png)

I don't know how you got iframes working yet and if it would be possible to break out of them to place hints in the main viewport container. I know there are security settings for this but curious for your take on it.

**Comment by david-tejada** [comment]
This is a weird one 😅. I don't use Jira so I can't test. Would you mind trying to set the attribute readonly to the hints to see if the issue goes away? Maybe you can do it in the devtools to see if it works. 

Making it work for iframes was just a matter of setting all_frames to true in the manifest so the content scripts get executed in all frames. Then I store the hints and to which frame it belongs in the background script. It's all a bit more convoluted now because I have to use local storage to support manifest v3. In theory I believe I could move all the hints to the main frame if I also stored the coordinates but it would not be trivial

**Comment by richardmcmillen** [comment]
You mean add `readonly="true"` on individual hints? I did that and they still ended up in the submitted content. :(
It's not a huge deal for me and I understand how much extra complexity this could add, so I am happy if you want to close this.

**Comment by david-tejada** [comment]
Could you try setting the div container to `<div id="rango-hints-container" contenteditable="false" readonly="readonly">`?

**Comment by richardmcmillen** [comment]
That doesn't change the behaviour either.

**Comment by david-tejada** [comment]
Ok. Thanks for trying. Let's leave this issue open for now. I'll see if I can come up with something.

**Comment by richardmcmillen** [comment]
No problem.

I'm pretty sure the editor is TinyMCE from what I can see from the DOM and
searching info about Jira. I then tried googling to see if there are any
classes you can add to elements which the lib would ignore/exclude when
grabbing content but I didn't see anything. It would be fine if they didn't
attach the editor to the  `body`, it is unfortunate.

**Comment by david-tejada** [comment]
I'm thinking a possible solution could be not to display hints in frames where the whole body is contenteditable.

**Comment by richardmcmillen** [comment]
Oh I like that nice and simple idea! Hopefully that wouldn't cause much confusion or oddness for anyone else.

**Comment by david-tejada** [comment]
I've tested it in [this TinyMCE example page](https://www.tiny.cloud/docs/demo/basic-example/) and seems to work nicely.

**Comment by david-tejada** [comment]
Will be available in v0.2.0 that I will release soon

**Comment by richardmcmillen** [comment]
This is working great!! Thanks heaps

<img width="731" alt="image" src="https://user-images.githubusercontent.com/298026/175439879-a8baf044-c497-4c6f-acfa-be62892aca72.png">

**Comment by richardmcmillen** [comment]
Oh that's quite a nice and simple idea!

**Comment by david-tejada** [comment]
From version 0.3.0 on this issue is not present. The hints are rendered but they will not be submitted or appear if you copy the text. Hints are rendered using shadow dom, what avoids the issue altogether.
