### ISSUE TITLE
Is there a way to make the mouse right click on a hint?

### ISSUE THREAD

**Issue by therealrobster** [david-tejada/rango#207]
I have had a good look around but I can't find anything on this.

I have a situation where I need to copy an email address from a link.

However this link has a BCC in it and a subject. So if I copy the link using Rango, it copies the email and the subject and all of it.

So, I'm having to move my mouse to the link, then I say righty, then I say go down third, then say enter.

In the same way that I can say focus and a hint, I'd really love to be able to say right click and the hint.

Is this something that can be done?

**Comment by david-tejada** [comment]
Not yet, I need to implement #107 for this

**Comment by david-tejada** [comment]
Closing this as duplicate of #107

**Comment by david-tejada** [comment]
I forgot. There is a way to trigger the context menu if you're on Windows
