### ISSUE TITLE
saying "click air second" does not click the hint "aa"

### ISSUE THREAD

**Issue by gpunktschmitz** [david-tejada/rango#208]
one can say [air second](https://github.com/david-tejada/rango-talon/commit/08e5f17b9bce19f7bfc9430d9fd88987cfffb078) to select the hint `aa`  but one cannot say `click air second` which is sometimes needed to click an element while the cursor is focused in a text input element and is way easier to say than `click air air` (which does work)

**Comment by david-tejada** [comment]
This is on purpose. Right now there are three ways for clicking an element with a hint like "aa": `air air`, `air twice` (or `second`) and `click air air`. At the same time there is only one way of clicking an element with the hint "a" twice: `click air twice`. This is not a very common case but I have used it in the past, for example, to add two items to a cart like this I could say `click jury twice`:

<img width="307" alt="Screenshot 2023-10-15 at 11 38 10" src="https://github.com/david-tejada/rango/assets/3219671/1338737a-4fba-4ed6-9605-6397f0b57dea">

There are two solutions for this. I can add a setting to exclude hints with repeated letters or you can add the next line to your *rango.talon*:

```talon
click <user.rango_hint_double> (twice | second): user.rango_command_with_target("clickElement", rango_hint_double)
```

**Comment by david-tejada** [comment]
I have fixed that capture because it was bothering me. I don't know why I did it like that. If you pull rango-talon the command you have to add would be:

```talon
click <user.rango_hint_double>: user.rango_command_with_target("clickElement", rango_hint_double)
```

**Comment by gpunktschmitz** [comment]
thanks! I just added the line and it works perfectly fine.
