### ISSUE TITLE
Ability to hide rango hints per tab

### ISSUE THREAD

**Issue by richardmcmillen** [david-tejada/rango#21]
https://github.com/david-tejada/rango/issues/20  means that I frequently have to hide/show rango hints when jumping around tabs as I spend a lot of time in Confluence and Jira where this is a problem. It would be great if I could toggle the hints per tab to not have to deal with that.

Also a sidenote, I find when I toggle the rango hints it seems to cause some significant work for my browser and it lags for a bit. I wonder if this is due to having multiple tabs open and rango having to do a lot of work to show all the hints after them being toggled off? Being able to toggle per tab would also help with that.

**Comment by richardmcmillen** [comment]
Another reason why this would be good is that I very often take screenshots of webpages, and want to remove the visual confusion for people not familiar with rango. I often toggle them off, take screenshot, toggle back-on (but then subject to laggy browser). Being able to do this per tab would be handy.

**Comment by david-tejada** [comment]
Good idea. I think this won't be hard to implement. I think I can also eliminate the lag when toggling hints by using `window.requestIdleCallback()`. While I'm at it I think I'll add a command to disable hints per domain. I think that will be useful for your use case.

**Comment by richardmcmillen** [comment]
Thanks! Feel free to say you don't have time to work on issues I log and I can see if I can hack away an implementation if you like.

>I think I can also eliminate the lag when toggling hints by using window.requestIdleCallback()

Interesting, that seems like it could help. Another idea I was thinking of was to only worry about the currently focused tab, and then as other tabs are focused (I am assuming there would be a tab focus event you could listen to) only then perform the required work to display hints. It would mean a slight delay on showing hints in freshly visited tabs after toggling them on again but perhaps even more performant for the tab you do have focused initially (rather than worrying about all the other ones as well). Perhaps more scalable for those with many many tabs as well, only doing the work as required. Perhaps toggling hints globally may be a less common occurrence though with the addition of https://github.com/david-tejada/rango/issues/21  

>While I'm at it I think I'll add a command to disable hints per domain. I think that will be useful for your use case.

Oh that could also be useful, though I think the other suggestion here https://github.com/david-tejada/rango/issues/20#issuecomment-1149523959 would really be ideal for me, avoiding the issue with iframes but still allowing me to use Rango on pages with the problematic elements. But this would be a good feature for sure.

**Comment by david-tejada** [comment]
OK. I already fixed the lag in main. The "hints toggle" code was a mess. I had every tab and every frame change the setting in local storage so it's a misery to me why this even worked sometimes 😅. Now it works great. First I update the hints in the active tab and then the rest with requestIdleCallback. Next I'll implement per tab and domain. It shouldn't be too hard.

Please keep filing issues. I enjoy the communication and appreciate your input. I work on this full time so I have time. It might seem like progress is slow but I've been improving the code a lot and have some good stuff coming soon. Implementing new features should take less time now.

**Comment by richardmcmillen** [comment]
haha 😅 sounds great!!
And I wouldn't say progress has been slow at all!! Thanks again.

**Comment by david-tejada** [comment]
Implemented in v0. 2.0
