### ISSUE TITLE
some hints open in a new tab when they shouldn't

### ISSUE THREAD

**Issue by ghost** [david-tejada/rango#213]
right now, saying the hint for a channel name in discord opens it in a new tab, which isn't what happens when I click on it. observed on firefox 115.3.0esr

**Comment by david-tejada** [comment]
I see. No idea why they're using `target="_blank"` if the link is supposed to open in the current tab. I will have to add an exception just for Discord.

**Comment by david-tejada** [comment]
This isn't completely fixed. I was relying on those links having a certain class but this is not reliable. For Discord, I think opening all internal links in the same tab and all external links in a new tab is going to be safer.

**Comment by brollin** [comment]
FWIW, just a day or two ago I noticed a change where now I can't switch to a different discord channel via "flick" anymore. Nothing happens when I try to do so. Using the normal clicking method still opens it up in a new tab.

**Comment by david-tejada** [comment]
It looks like they made those links not focusable. No idea why they did that.

**Comment by brollin** [comment]
Thanks a ton for this fix! :)
