### ISSUE TITLE
open link in new tab

### ISSUE THREAD

**Issue by asoee** [david-tejada/rango#22]
it would be nice, if you could open links in a new tab
like control+click

**Comment by richardmcmillen** [comment]
@asoee this should already be possible with Rango! https://github.com/david-tejada/rango#other-commands

`blank <hint>: It opens the link in a new tab.`

**Comment by david-tejada** [comment]
You already can open links in a new tab. Soon I'll implement opening links in a new tab without stealing focus. I think I'll implement #25 directly. This will address this issue and #24 wich is essentially the same

**Comment by david-tejada** [comment]
I implemented this. The command is `stash` and takes one or more hints and opens them in a new tab without activating it. Will be in v0.2.0 that I'll publish next week.
