### ISSUE TITLE
Bookmarks are Titled with Labels

### ISSUE THREAD

**Issue by jcaw** [david-tejada/rango#224]
When bookmarking a page in Firefox, if Rango is active, the title of the bookmark will include Rango's tab labels.

**Comment by david-tejada** [comment]
I might be able to add a `bookmarks.onCreated` event listener and remove the tab marker if it has one.

**Comment by david-tejada** [comment]
I managed to solve this. It will remove the tab markers and the url added by Rango when saving bookmarks. It won't work in Safari as it doesn't support the bookmarks API.

**Comment by jcaw** [comment]
That's awesome! Thank you.
