### ISSUE TITLE
Ability to copy clickable element text to clipboard

### ISSUE THREAD

**Issue by richardmcmillen** [david-tejada/rango#23]
Rango has the ability to copy link urls to clipboard.
I think it would be useful to be able to copy the clickable elements text content to clipboard as well.
For example: 

https://docs.aws.amazon.com/rds/index.html
![image](https://user-images.githubusercontent.com/298026/172594620-3a5b5020-f39c-415d-835a-6472fd989f0a.png)

`copy text pit` => `Performance Insights in the AWS CLI Reference` would be put in the clipboard.

This is getting a bit into cursorless style territory but maybe not too much to implement.

**Comment by david-tejada** [comment]
This should be very easy to implement. I'll get to it soon

**Comment by david-tejada** [comment]
Implemented in v0. 2.0
