### ISSUE TITLE
Ability to define whether or not links opened in new tabs become focussed

### ISSUE THREAD

**Issue by richardmcmillen** [david-tejada/rango#24]
I think this means being able to set the `selected` value  https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create when creating the tab here https://github.com/david-tejada/rango/blob/b90edaa346db93cf29423ef91b28450e6aa0e39d/src/background/tabs-messaging.ts#L90 as it defaults to true.

I am unsure what to suggest for the Talon command, and whether or not it should share the existing `blank ...` command with an extra qualifier or if it should get a new one. I think I'm leaning towards a new word, some for consideration:

```
stash air
load air
set air
store air
pack air
```

Trying to think of words which invoke imagery of stashing something away for later use as is common with opening links in new tabs

**Comment by david-tejada** [comment]
I already had this in mind. I like `stash`. I think I'll implement this one and #25 all at once

**Comment by david-tejada** [comment]
I implemented this. The command is `stash` and takes one or more hints and opens them in a new tab without activating it. Will be in v0.2.0 that I'll publish next week.
