### ISSUE TITLE
alternative visual indicator for if a hint is included or excluded

### ISSUE THREAD

**Issue by ghost** [david-tejada/rango#249]
right now, the only indicator of if you've excluded or included a hint (before you save) is by the colour of that hint- which is usually fine, but can cause issues if you're colourblind, or you use a greyscale monitor.  having the option for an alternative visual indicator would be nice, like for example adding a tick or a cross to the hint, or giving an excluded hint a dotted outline or something.

Example of how hints look in greyscale:
![an included and excluded hint with the screen set to grayscale- the two are almost identical](https://github.com/david-tejada/rango/assets/60542090/c3908ab3-7c1a-4a85-a7f6-6cc6baf4f4e2)

**Comment by david-tejada** [comment]
Makes sense. I will try and see what works best.
