### ISSUE TITLE
Open multiple links in new tabs in one utterance which don't steal focus

### ISSUE THREAD

**Issue by richardmcmillen** [david-tejada/rango#25]
_Related to https://github.com/david-tejada/rango/issues/24 but it seems like a large enough issue to have tracked separately._

Once we can open links which don't take the focus of the window it would be cool to be able to open N number of links in one Talon utterance.

With rango direct clicking enabled, and hints `a`,`b`,`c`,`d` present on the page.

Saying `*stash air and bat and cat` would open the three links identified by those hints in new tabs but the original tab remains the focussed one.

`*stash` to be replaced with whatever the outcome of https://github.com/david-tejada/rango/issues/24 is.

**Comment by david-tejada** [comment]
I implemented this. The command is `stash` and takes one or more hints and opens them in a new tab without activating it. Will be in v0.2.0 that I'll publish next week.
