### ISSUE TITLE
rango hints break filter options on https://media.ccc.de

### ISSUE THREAD

**Issue by gpunktschmitz** [david-tejada/rango#263]
when using rango on that page the sorting header breaks and becomes unreadable - for example: https://media.ccc.de/c/37c3?sort=date

disabling rango hints shows the blue filter options correctly.

**Comment by david-tejada** [comment]
This page has some weird layout using `display: table`, floats, some strange `width: 1%`,... It all looks very hacky.

I have have a fix that involves never placing hint elements within tables. I will test for a while to see that nothing else breaks.
