### ISSUE TITLE
Timing issues with updating tab title

### ISSUE THREAD

**Issue by richardmcmillen** [david-tejada/rango#27]
I am not sure what could be going on here but when I visit this website: https://registry.terraform.io/providers/hashicorp/aws/latest/docs

The title ends up being ` - https://registry.terraform.io/providers/hashicorp/aws/latest/docs`

Which smells like a race condition with updating the window title, maybe some client side code by the website VS rango.

In a different browser I can see how the tab does have an original title, which is then updated after some time presumably by some client side code.

It starts out as:

 - Terraform Registry
and then is updated to
 - Docs overview | hashicorp/aws | Terraform Registry

But in Firefox with rango it just ends up being: ` - https://registry.terraform.io/providers/hashicorp/aws/latest/docs`

**Comment by david-tejada** [comment]
I fixed this by checking that the title is not an empty string before adding the URL to the title.
