### ISSUE TITLE
Add PayPal donation option

### ISSUE THREAD

**Issue by falzonv** [david-tejada/rango#283]
Hello,

Thank you very much for having created this web extension!
I am still discovering Talon (learnt about it 2 weeks ago) but Rango indeed integrates very well with it, and adds several interesting features lacking in Vimium, the hints also look better. Great work!

Looking for how to support the project, it seems only possible via GitHub sponsorship but I am not really willing to provide my financial info to GitHub which I use only for development purposes.
Would it be possible to add a PayPal link?

*(you can see an example of how the PayPal donation interface looks like with my link in https://github.com/falzonv/discreet-launcher, there are also various customization options)*

Best regards.

**Comment by david-tejada** [comment]
Thanks! I'm glad you're finding the extension useful. I will add the option to donate with PayPal
