### ISSUE TITLE
nut.js changed to monorepo and is breaking npm install

### ISSUE THREAD

**Issue by bacall213** [david-tejada/rango#289]
@nut-tree/nut.js appears to have changed to a monorepo and it's breaking the nut.js dependency:

It looks like the change was made around here: https://github.com/nut-tree/nut.js/commit/e12635d8f2bfd0dea8b7f56088c09a2bed2a1c32

When running npm install with no cached packages, it returns:

`Not Found - GET https://registry.npmjs.org/@nut-tree/nut-js/-/nut-js-3.1.1.tgz - Not found`

It doesn't look like the repo has been re-exported to NPMJS yet.

**Comment by david-tejada** [comment]
Ok. I'll take a look.

**Comment by bacall213** [comment]
It looks like someone beat me to asking about it on the nut.js git repo: https://github.com/nut-tree/nut.js/issues/591. Hopefully the nut.js owner will re-export the new package to npmjs. 

If you want to see the error yourself, move your npm package cache and package-lock files out of your build directory and then try pulling down the NPM dependencies. 

I don't expect you to need to do anything unless they change the exported package name for @nut-tree/nut.js. This issue issue has more to do with nut.js, but I dropped a note here for your awareness.

**Comment by smithkyle** [comment]
He's not offering public packages anymore - see his most recent blog post. You need to build it yourself now :/
