### ISSUE TITLE
Add scrolling

### ISSUE THREAD

**Issue by david-tejada** [david-tejada/rango#3]
- [x] A command for scrolling an specific element: We will need to find the closest ancestor with overflow.
- [x] Add commands for scrolling an element to a certain position (top, center , bottom)

**Comment by zareami10** [comment]
This sounds great, especially if we could have actions similar to Cursorless (e.g. center x, top x, bottom x, etc) for precise scrolling usually not possible without a mouse.

**Comment by david-tejada** [comment]
Oh, great idea, @zareami10

**Comment by david-tejada** [comment]
Implemented in v0. 2.0

**Comment by zareami10** [comment]
> Implemented in v0. 2.0

Thanks, but it seems we still can't scroll relative to a element such as in Cursorless, unless I'm missing something.

**Comment by david-tejada** [comment]
Sorry, I'll try to work on that.

**Comment by david-tejada** [comment]
@zareami10 take a look at this. Is this what you were expecting? I even take into account the space occupied by sticky headers. You can see the commands up top. My letters are a bit different but I think you'll understand.
![Peek 2022-06-25 17-07](https://user-images.githubusercontent.com/3219671/175779655-b8b3ff13-ad6c-48f8-9946-49166540e94f.gif)

**Comment by zareami10** [comment]
> @zareami10 take a look at this. Is this what you were expecting? I even take into account the space occupied by sticky headers. You can see the commands up top. My letters are a bit different but I think you'll understand.

Yes, looking great!
Thanks a lot for the work!

**Comment by david-tejada** [comment]
Great! I'll probably publish a new version with this and a couple more improvements next week
