### ISSUE TITLE
Toast notifications could use improved contrast

### ISSUE THREAD

**Issue by bacall213** [david-tejada/rango#305]
The toast notifications utilize '--toastify-text-color-light' as the foreground color. For the footer, in particular, the combination of `--toastify-text-color-light` (#757575) as a foreground on a background of #E5E5E5 results in lower than ideal contrast that can make the message hard to read. I'm not sure what toastify color variables are available to you so I don't have a drop in replacement. Replacing `--toastify-text-color-light` with pretty much anything darker would be enough. 

The problematic CSS is included in `src/content/notify/Toast.css` under `#rango-toast .Toastify__toast-body footer code { }`

**Comment by bacall213** [comment]
It looks like --toastify-text-color-light is defined in Toastify's [_variables.scss config](https://github.com/fkhadra/react-toastify/blob/801a3ea6d19402a86c3fc6be4fc832e1cfad2d62/scss/_variables.scss#L31). You could override it locally, or perhaps use --toastify-color-dark: #121212;

**Comment by david-tejada** [comment]
Okay, I'll fix it

**Comment by bacall213** [comment]
#371 Fixes this :)
