### ISSUE TITLE
Setting to use upper case hint letters

### ISSUE THREAD

**Issue by AndreasArvidsson** [david-tejada/rango#31]
I think that upper case letters would be easier to distinguish

**Comment by AndreasArvidsson** [comment]
* [ ] it would also be nice if there were a setting where you could give a whitelist of all the characters you want to use. For example if two letters look too much alike you can exclude one of them. It would also allow us to add symbols to the hints if we wanted.

**Comment by awulkan** [comment]
I would also love to have this feature since it's really difficult to read the small letters.
Another thing that makes it more difficult to read letters is that the contrast is sometimes very low.

**Comment by david-tejada** [comment]
Yes, this is on the roadmap for when I implement ui settings. I'll get to than once I finish with the stable hints rewrite.

**Comment by awulkan** [comment]
Awesome, thanks for all of the work you are putting into this. The extension is really good!
