### ISSUE TITLE
Tab markers cause issues with non-HTML tabs in Safari (or those where `document.title` is empty?)

### ISSUE THREAD

**Issue by nriley** [david-tejada/rango#310]
There are two issues with tab markers when viewing PDFs, text files, etc. in Safari.

1. Rango replaces the tab title with the tab marker so you can no longer see from the title what the tab contains. I notice that `document.title` is empty to start. So you can see the tab marker but not the title — which appears as `document.location`, but is **not** equivalent to setting `document.title` to `document.location`; see below. Here's how a tab title appears on a PDF: <img width="49" alt="image" src="https://github.com/user-attachments/assets/d9def190-a853-4ac1-b5f4-2245b9117190">

2. Safari uses the tab title as the default filename when saving. This means I get the tab marker as a filename, instead of the actual (e.g.) PDF filename. Example: <img width="313" alt="image" src="https://github.com/user-attachments/assets/e07741fb-8d73-46ef-9379-7565b713ddaf">

If I try to set `document.title` to `document.location`, the default filename becomes the *entire* URL not just the filename, so that's not an option.

One option (not sure whether Rango can do this?) might be setting `document.title` to `""` *when the tab is active*, thus restoring correct behavior when saving, and setting `document.title` to the tab marker plus `document.location` when the tab is in the background, such that it can be targeted by voice.

**Comment by david-tejada** [comment]
Nice find! It seems we get the same behaviour in Chrome, although just the first part, saving seems to be fine. And for whatever reason Firefox doesn't seem to let content scripts run anymore on PDFs.

I think the solution you propose looks fine. It should work and I think it's possible to implement.
