### ISSUE TITLE
Fix bug with duplicated hints

### ISSUE THREAD

**Issue by AndreasArvidsson** [david-tejada/rango#41]
In gmail for example I occasionally have a duplicate hint on the right hand side panel

**Comment by david-tejada** [comment]
I managed to fix this by, after each hints update, check if there's duplicate hint nodes and doing a full hints refresh if that's the case. It's not ideal and I would like to find the root cause but the issue is hard to reproduce

**Comment by AndreasArvidsson** [comment]
Nice!
Couldn't you check for duplication before assigning a hint and then chose another combination of characters?

**Comment by david-tejada** [comment]
That's another alternative, but then I'd had to loop through all the hints everytime I assign one. I figured is cheaper just to check once at the end

**Comment by AndreasArvidsson** [comment]
I was thinking you could use a hash set or something efficient like that. Maybe with the message system it requires it's still problematic. You know the code better than I do :)

**Comment by david-tejada** [comment]
Yes, probably a set would be quick enough but I'd need to ask the background script for a new hint and it would add unnecessary complexity. This way if we find a duplicate hint we just reset everything. 

But I think checking before assigning a hint would be a good way to find the cause of the issue. I can add a breakpoint and see the state that led to that. Going to Gmail and scrolling up and down usually produces the error, it might take a couple of minutes of scrolling and clicking around but at least I can reproduce it.

**Comment by AndreasArvidsson** [comment]
Sounds like a plan!
