### ISSUE TITLE
Hints look a little jittery/twitchy since 0.2.0

### ISSUE THREAD

**Issue by richardmcmillen** [david-tejada/rango#49]
In the process of debugging https://github.com/david-tejada/rango/issues/28 I checked out version `v0.1.9` at `57f216a`. In unrelated to that issue I did notice that the `v0.2.0` version does result in the hints being a little more jittery than version version `v0.1.9` when scrolling.

I used this page for testing: https://en.wikipedia.org/wiki/Main_Page

I had noticed this when `v0.2.0` was released but didn't bring it up, going back to the older version it is pretty clear though.

I am unsure how the rendering/positioning/throttling code has changed between versions and this may be a conscious decision compromising between smoothness and performance. But thought I would bring this us up if not.

Here is a quick screen recording showing how it looks for me: https://www.youtube.com/watch?v=AEfzh33mrjY

**Comment by david-tejada** [comment]
You are right. I had noticed the hints being jumpy too. I'm going to try to fix this as best as I can but I think the best solution is going to be implementing #44
