### ISSUE TITLE
Add option to configure the scrolling behavior

### ISSUE THREAD

**Issue by dyancat** [david-tejada/rango#65]
Currently Rango scroll commands will immediately move the windows contents to the scroll destination which can be jarring.

It would be nice if we could enable smooth scrolling so that the content visually transitions to new scroll position.

**Comment by david-tejada** [comment]
Starting with v0.3.1 the scrolling behavior is smooth unless the user has configured the OS to prefer reduced motion. [prefers-reduced-motion - CSS: Cascading Style Sheets | MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion#user_preferences)

I will leave this open until I add a preference, anyway.

**Comment by david-tejada** [comment]
From v0.3.5 you can customize the scrolling behavior in the settings.
