### ISSUE TITLE
Linux Mint Firefox Crashes After Rango Fails to Handle Talon Command

### ISSUE THREAD

**Issue by Madhav-Malhotra** [david-tejada/rango#80]
### Problem
I have this weird bug where Rango will work fine for about 40 mins, but then crash after I say a command. When it crashes, my Firefox window goes black and my taskbar at the bottom of the screen disappears so that I'm left seeing my desktop. My keyboard isn't responsive, but I can click around for a bit and then the black Firefox window shows the site I was on again. And the site it is responsive to my clicks, just not my keyboard. When I try further Talon voice commands, **I see subtitles appearing, but the commands have no action.**

**I talked to aegis about this. When I showed him the crash logs, he told me that Talon was recognising my voice input fine, but Rango was failing to handle the command issued**. I added the crash logs below as images (sorry I couldn't copy the text or take a nicer screenshot - my computer wasn't responding to inputs). 

![trace 1](https://imgur.com/RKktKAd.jpg)
![trace 2](https://imgur.com/PgUJ6L2.jpg)
![trace 3](https://imgur.com/xiEUIq0.jpg)
![trace 4](https://imgur.com/ZHeVYeZ.jpg)

### Environment:
- Linux Mint 21.3 
- Firefox 109.0.1 (64-bit), 
- Talon version: the one available under [latest](https://talonvoice.com/dl/latest/talon-linux.tar.xz))
- Rango version: [0.3.1](https://github.com/david-tejada/rango/releases/tag/v0.3.1)
- Rango Firefox Extension version: [0.3.1](https://addons.mozilla.org/en-US/firefox/addon/rango/)

### Attempted Solutions
I've tried reinstalling talon (and knausj, cursorless, rango, and my speech recognition engine) three times. The issue started occuring when

**Comment by david-tejada** [comment]
I haven't seen anything like this before. I don't know if the extension could crash Firefox in such a way. When it crashes, is it always after saying a Rango command?
Do you have any firefox crash reports in about://crashes?

**Comment by Madhav-Malhotra** [comment]
Update: as we talked about in the Talon Slack, it's probably a hardware issue.
