### ISSUE TITLE
"Downer" doesn't work on hacker news

### ISSUE THREAD

**Issue by Surreal9** [david-tejada/rango#94]
For example, go to https://news.ycombinator.com/item?id=35640002 and say "downer", and it scrolls down crazy far. This is the only site I've seen this behaviour so far.

**Comment by david-tejada** [comment]
I see, there's an issue with the way I calculate the viewport dimensions. I need to fix that. Probably the same reason scrolling is sometimes janky in slack. Thanks for the issue, I'll fix it soon
